export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
// export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const LOADING = "LOADING";

// export const ADD_FAVORITE = "ADD_FAVORITE";
// export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
// export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
